export const Auth = {
    FETCH: "FETCH_TOKEN",
    FETCH_SUCCESS: "FETCH_TOKEN_SUCCESS",
    FETCH_REGISTER: "FETCH_REGISTER",
    FETCH_ERROR: "FETCH_TOKEN_ERROR",
    LOGOUT: "LOGOUT",
    SET_ERROR: "SET_ERROR",
  };
  